### ISSUE TITLE
Search for Videos

### ISSUE THREAD

**Issue by msaulohenrique** [prof18/YoutubeParser#1]
How can I add a search for videos based on your module?

**Comment by prof18** [comment]
Hi,

that's a nice feature to add! There could be two way to search in the video item. The former is to search across the json file, the latter is to search across the video items in the list. If you follow the first way, you need to rewrite a part of the library but if you follow the second all you need to do is to compare the input keyword with the title of the video.

**Comment by msaulohenrique** [comment]
Would it be possible to list all the videos?

**Comment by prof18** [comment]
Actually the maximum size is 50 items, because i forgot to implement a request to the next page of result. So very thank to you to pointing me that, i'll implement it soon!

**Comment by MaheshCapcee** [comment]
Hello sir are you finished this issue ?

**Comment by prof18** [comment]
No, unfortunately I had some problem with work and university stuff, so the release is delayed

**Comment by prof18** [comment]
Hi, I've released a new update of the library that resolves this issue and also add the possibility to get the statistics of the video. Give a look to the readme for more info.
