### ISSUE TITLE
Demo app doesn't work

### ISSUE THREAD

**Issue by javierbentez** [prof18/YoutubeParser#10]
Hi! I have tried to use the demo app but doesn't get any video. Maybe something need an update or I'm doing something wrong. Can u help me please?

**Comment by prof18** [comment]
Sorry for the late reply. 

Did you create an API key for the youtube API from [the Google Console](https://console.developers.google.com)?

More resources about it:
- https://developers.google.com/youtube/v3/getting-started
- https://blog.hubspot.com/website/how-to-get-youtube-api-key
