### ISSUE TITLE
get like and length

### ISSUE THREAD

**Issue by MaheshCapcee** [prof18/YoutubeParser#2]
hello how to get like and length of video

**Comment by prof18** [comment]
Hello. Actually it's not possible, but i've planned to add this features. I hope that i can add it in a few time.

**Comment by MaheshCapcee** [comment]
thank you

**Comment by prof18** [comment]
Hi, I've released a new update of the library that add the possibility to get the statistics of the video. For now I'm not able to get the length of the video, but I'm thinking how to handle it. Give a look to the readme for more info.

**Comment by MaheshCapcee** [comment]
Hi, Ok thank you very much
