### ISSUE TITLE
Problem adding more than 50 items in list

### ISSUE THREAD

**Issue by varunsngl** [prof18/YoutubeParser#3]
Hi,

Thanks for publishing such a wonderful project. But there is a problem my channel has around 73 videos and we publish 5 videos every week. Please add an option to add more videos and also will be best if you also add an option to endless scroll the videos.

Thanks again for providing such a great help :)

**Comment by prof18** [comment]
Hi, I'm already working on that feature. In this period I'm very busy, but I'm trying to release this feature as quickly as possible.

**Comment by prof18** [comment]
Hi, I've released a new update of the library that resolves this issue and also add the possibility to get the statistics of the video. Give a look to the readme for more info.

**Comment by varunsngl** [comment]
Thanks a lot
