### ISSUE TITLE
İt is not working 

### ISSUE THREAD

**Issue by slomxx** [prof18/YoutubeParser#4]
Hello 

I downloaded your apk. 

But it is not working.
Can u check it. 

Thanks.

**Comment by prof18** [comment]
You're right! In this example I'm using an old API Key and probably is not valid anymore. I'll check it ASAP.

**Comment by prof18** [comment]
Hi,
i've just fixed the broken apk. Sorry for the problem and for the delay.

**Comment by slomxx** [comment]
Thank you so much 👍
